openapi: 3.0.1
info:
  title: Order Pizza API
  description: A REST-ful API for pizza ordering.
  version: "1.0"
servers:
  - url: /api
paths:
  /auth:
    post:
      tags:
        - Auth
      summary: Create an access token
      description: Create an access token for user to login
      operationId: auth.login
      requestBody:
        description: token to create
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: password of user
                username:
                  type: string
                  description: username of user
        required: true
      responses:
        200:
          description: Successfully created token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token used for authorisation
  /orders:
    get:
      tags:
        - Orders
      summary: Return list of Pizza orders
      description: Read the entire set of orders, sorted by timestamp.
      operationId: orders.read_all
      responses:
        200:
          description: Successfully read orders set operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Crust:
                      type: string
                      description: Crust for the pizza
                    Flavor:
                      type: string
                      description: Flavor of the pizza
                    Order_ID:
                      type: integer
                      description: Id of the order
                    Size:
                      type: string
                      description: Size of the pizza
                    Table_No:
                      type: integer
                      description: Customer's table number
                    Timestamp:
                      type: string
                      description: Creation/Update timestamp of the order
    post:
      tags:
        - Orders
      summary: Create an order
      description: Create a new person
      operationId: orders.create
      requestBody:
        description: Order to create
        content:
          application/json:
            schema:
              type: object
              properties:
                Crust:
                  type: string
                  description: Crust for the pizza
                Flavor:
                  type: string
                  description: Flavor of the pizza
                Size:
                  type: string
                  description: Size of the pizza
                Table_No:
                  type: integer
                  description: Customer's table number
        required: true
      responses:
        201:
          description: Successfully created order
          content:
            application/json:
              schema:
                type: object
                properties:
                  Crust:
                    type: string
                    description: Crust for the pizza
                  Flavor:
                    type: string
                    description: Flavor of the pizza
                  Order_ID:
                    type: integer
                    description: Order number
                  Size:
                    type: string
                    description: Size of the pizza
                  Table_No:
                    type: integer
                    description: Customer's table number
                  Timestamp:
                    type: string
                    description: Timestamp of when the order was made
        401:
          description: Authorisation unsuccessful
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Missing Authorization Header
  /orders/{Order_ID}:
    delete:
      tags:
        - Orders
      summary: Delete an order from the orders list
      description: Delete an order
      operationId: orders.delete
      parameters:
        - name: Order_ID
          in: path
          description: ID of order to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successfully deleted an order
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Order deleted success message
        404:
          description: Order not found to delete
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Contains Order ID that was not found
                  status:
                    type: integer
                    description: HTTP Status, will be 404
                  title:
                    type: string
                    description: Title of the the 404
                  type:
                    type: string
                    description: type
components: {}
